[package]
name = "ferrodb"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p = "0.39.1"
futures = "0.3.15"
env_logger = "0.9.0"
async-std = { version = "1.9.0", features = ["attributes"] }